### ISSUE TITLE
Is it possible to remove the padding from within the SVG?

### ISSUE THREAD

**Issue by bhellman1** [naikus/svg-gauge#10]
Amazing work... I'm noticing that all the SVGs generated with gauges have padding within the SVG, is it possible to have the gauge use the all the space in the SVG?

Given that the gauge currently has some random padding within the SVG it makes it near impossible to create an SVG that matches a design.

Thanks again for this, appreciate any tips. Thanks

**Comment by naikus** [comment]
Hi @bhellman1, Thanks!
There is an option call ```dialRadius```. Its default value is 40 i.e. (gauges viewbox (100) / 2 - 10). You can change it in the gauge's constructor function with this option. Set it to 49:

I missed it in the documentation somehow :) I'll put it in the README

```javascript
var gauge1 = Gauge(
  document.getElementById("gauge1"), {
    dialRadius: 49, // This will make the gauge's dial flush with the svg element
    ...other options
  }
);
```

**Comment by bhellman1** [comment]
Strange, when I set dialRadius to 49, the gauge grows to fit outside the SVG resulting in the gauge being cut off.

**Comment by naikus** [comment]
@bhellman1  The value you set will depend on the stroke width of your dial. Play around with different values. e.g. In the online demo on codenpen.io, for gauge2, the dial radius needs to be set as ```dialRadius: 42.5``` because the stroke width is 10
