### ISSUE TITLE
Is there a color option for setting the value of the dial (bkg color)?

### ISSUE THREAD

**Issue by bhellman1** [naikus/svg-gauge#11]
The option color works great for setting the color of the value. Is there a option to dynamically set the color for the bkg dial?

It would be great if given an existing gauge you could perform:

```
setGaugeValueColor
setGaugeDialColor

```
just like you can currently perform `setValueAnimated`

**Comment by naikus** [comment]
@bhellman1 Unfortunately, the gauge does not have an option to set the dial background color dynamically. But you can set the dial value color dynamically by using the ```color: function(value) {}```. In the online demo you can see gauge2 doing this.

**Comment by bhellman1** [comment]
appreciate the speedy reply. I'll have to see how I can make this happen :)
