### ISSUE TITLE
SpaceX Gauge customization

### ISSUE THREAD

**Issue by aleonnet** [naikus/svg-gauge#13]
Hi @naikus, great job!
This is not properly an issue, but how can I have the famous SpaceX gauge?

![image](https://user-images.githubusercontent.com/20618327/36940885-d560ad78-1f2c-11e8-8323-f21217dcd54e.png)

I can adjust the angles like below, but I don't see how to configure the unit for example
    dialStartAngle: 90,
    dialEndAngle: 0, 

Thank you

**Comment by naikus** [comment]
Hi @aleonnet, the gauge currently does not support multiline labels, there is an issue #9 tracking this and may be solved in the next release. But it is still possible to work around with the current version.
Take a look at the [codepen demo](https://codepen.io/naikus/pen/BzkoLL). I've updated gauge4 to look a bit like the above image. Note that the dial currently does not support multiple colors as you've depicted in the image above.

**Comment by aleonnet** [comment]
Thank you!
