### ISSUE TITLE
Editing and positioning svg

### ISSUE THREAD

**Issue by pawelklasa** [naikus/svg-gauge#17]
<img width="96" alt="screen shot 2018-04-24 at 14 56 54" src="https://user-images.githubusercontent.com/11976919/39191856-c04b750a-47cf-11e8-8ff4-5ed63b99c6c5.png">
I Have been trying to position that number right in the middle of the circle but it seems impossible without being able to amend the SVG itself. It would be nice if that was somehow possible.

**Comment by naikus** [comment]
Hi @pawelklasa, did you try CSS transform for the text element?

**Comment by naikus** [comment]
I'm closing this issue since this can be done via CSS transforms. Please re-open if it is not working for you.
