### ISSUE TITLE
Multiple values

### ISSUE THREAD

**Issue by MartinMuzatko** [naikus/svg-gauge#21]
Hey there.

I realize that there are no needles to display multiple values, but what would be the best way to indicate something like an average value as an indicator?

Thanks in advance!

**Comment by naikus** [comment]
Hi @MartinMuzatko Can you point me to an example? Thanks

**Comment by MartinMuzatko** [comment]
Hi there.

This is a primitive example, since - as I said - there are no needls in this component.

![image](https://user-images.githubusercontent.com/2950505/41990943-2c2ec0e6-7a44-11e8-8a76-d1f7b236c5ed.png)

What I want to achieve, is to indicate within that range (0-100) what the usual lower and upper bounds are. Or for example - an average value. 

I'm building a dashboard for visualizing IoT Devices/Sensors etc.
If you could point me to any component that is more ideal for that task, I'd be thankful. Either way: if you see a way to make this possible with this needle-less component, that would be great.

Best,
Martin

**Comment by naikus** [comment]
@MartinMuzatko I don't plan on supporting this "scale" feature. But as a workaround you may look at the "color" option. But I understand you want your gauge dial to indicate the range. Unfortunately its not possible :-)
Thanks,
Aniket
