### ISSUE TITLE
Circle-drawing definition?

### ISSUE THREAD

**Issue by mbusson** [naikus/svg-gauge#24]
I'm trying to decipher your code, which is very high-end for my standards. I like the simplicity of use, and the efficiency and performance of your plugin. I like it so much that I would like to extend it for my project to allow it to draw bars as well, reusing your code to animate and normalize it etc. (If I succeed I could send you my work, that you'd probably want to correct a bit since I'm way behind you in terms of knowledge and coding standards.) And though I understand a lot of the configuration you're doing, and most of the calculations, there's one thing that drives me crazy... How do you define that you are to draw a circle?

I need to find what method you use to define that the course of your SVG drawing is a line following the trajectory of a circle, and especially where you start the drawing process. And I've been failing at that all afternoon. I thought, why not ask straight-away? :)

If this question doesn't fit here, feel free to delete it (and thanks for reading me!)

Kindly,
Max

**Comment by naikus** [comment]
Hi @mbusson 
I'm caught up in some work and will answer your question in detail soon. Meanwhile its not a circle but an svg path. A function called ```pathString`` on line 219 draws the gauge value (the "circle") actually, an arc.
See this page of how arcs work.
https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths

Thanks,
naikus

**Comment by mbusson** [comment]
Hey Naikus, thank you so much for your answer! 

You've given me plenty to work with already, I remember that "d" attribute and it took me some time to ponder whether or not this was an important bit haha

I think I've taken enough of your time, I'll look into it again and in case I end up making something usable out of my fork I'll send you the results :) No need to spend too much time chaperoning me, I'll read the appropriate documentation and try to get my head inside your programming ;)

Thanks again!
Max
