### ISSUE TITLE
ViewBox

### ISSUE THREAD

**Issue by vladimir-kondratenko** [naikus/svg-gauge#29]
Hey. Are u planning add `viewBox` feature in the nearest future?

**Comment by naikus** [comment]
@vladimir-kondratenko Can you please elaborate? The gauge already uses a viewBox. Do you want to be able to configure the viewBox?

**Comment by vladimir-kondratenko** [comment]
@naikus doc says that u can pass `viewBox` field in options, but it doesn't work. ViewBox is static string in the source code.

**Comment by naikus** [comment]
@vladimir-kondratenko The viewBox is available in the master branch and not part of the release. I'll release it shortly,

Thanks,
Aniket

**Comment by abecks** [comment]
Hey @naikus did this ever get released? Just tried to use the `viewBox` option unsuccessfully.

**Comment by naikus** [comment]
@abecks I've published a new version to npm registry that fixes this
