### ISSUE TITLE
Add min/max value labels and maybe threshold value labels

### ISSUE THREAD

**Issue by spoon252** [naikus/svg-gauge#32]
I'll provide some pictures about my idea. I would like an option to add these value labels.

right now
![image](https://user-images.githubusercontent.com/42466865/58170129-eb85e180-7c92-11e9-9146-32aa8d486154.png)

with value labels 
![image](https://user-images.githubusercontent.com/42466865/58170264-36075e00-7c93-11e9-8860-96e88efed2fa.png)

is it already possible perhaps? please explain if it is 
Thanks
Emir

**Comment by naikus** [comment]
Hi @spoon252 This is currently not possible :)
You may add min and max labels via html and style them using css though.
