### ISSUE TITLE
Experiencing a ReferenceError: k is not defined (gauge.js)

### ISSUE THREAD

**Issue by coltenkrauter** [naikus/svg-gauge#33]
I am implementing this neat svg-gauge via the wrapper that @mattlewis92 made [here](https://github.com/mattlewis92/angular-gauge/)

I am experiencing a ReferenceError, `k is not defined` when I try to run my Angular 8 app with an svg-gauge in it. 

Per the console error, it seems that this is the line of code that I am battling: 
https://github.com/naikus/svg-gauge/blob/master/src/gauge.js#L96

Would you be able to modify this line (or I could create a PR..?), 

**FROM**
```
for(k in s) {
```
**TO**
```
for(let k in s) {
```

I am hoping that this will solve my problems. 
If you have any other advice, it will be much appreciated. 

Screenshot: 
![image](https://user-images.githubusercontent.com/18080897/62418853-396e7c80-b628-11e9-9f9a-df08ac9524b7.png)

https://angular-ssr-example.coltenkrauter.com
https://github.com/coltenkrauter/angular-ssr-example

**Comment by naikus** [comment]
Hi @coltenkrauter Thanks for reporting this! This has been fixed in 1.0.6 version of the library in npm.

**Comment by coltenkrauter** [comment]
Fantastic! Thanks @naikus for the quick response.

**Comment by coltenkrauter** [comment]
Lastly, @mattlewis92, will you update the svg-gauge reference in the angular wrapper to use version 1.0.6?

https://github.com/mattlewis92/angular-gauge/blob/master/package.json#L122

**Comment by mattlewis92** [comment]
@coltenkrauter released as `3.1.2` 😄

**Comment by coltenkrauter** [comment]
Thanks a lot @mattlewis92 - I can confirm, it is now working as expected. I really appreciate your helpfulness.
