### ISSUE TITLE
Animations not working in React

### ISSUE THREAD

**Issue by JoeRoddy** [naikus/svg-gauge#34]
Hi and thanks so much for making this!!

I was having issues getting my gauges to animate in a react project and thought maybe it was my setup.  I created a codesandbox and just pasted the exact react example from the readme and the animations still do not fire.

Animations seem to work fine in a pure JS project.

You can check out the code sandbox [here](https://codesandbox.io/s/mystifying-chebyshev-5wbts?fontsize=14).

Let me know if I'm doing anything wrong.

**Comment by JoeRoddy** [comment]
I realized the current example just never calls `setValue()` before calling `setValueAnimated()`, which was the reason for the missing animation.

**Comment by naikus** [comment]
Hi @JoeRoddy, I'll take a look into this and update the documentation.
Thanks!

**Comment by JoeRoddy** [comment]
Np! I submitted a PR with an updated react example that uses current syntax.  Let me know if you want me to tweak anything @naikus
