### ISSUE TITLE
Gauge label transform not working on Safari

### ISSUE THREAD

**Issue by cetorres** [naikus/svg-gauge#40]
The gauge label, which is svg <text>, doesn't work (gets ignored) when we try to apply a class with a transform inside. 
The solution is to add the <text> inside a group: <g><text></text></g> and apply to the class the group.

**Comment by naikus** [comment]
Thanks for reporting this. I'll look into your solution.

**Comment by naikus** [comment]
Hi @cetorres This has been fixed in master

**Comment by naikus** [comment]
Thanks @cetorres for your solution!
