### ISSUE TITLE
CSS for value-text not working

### ISSUE THREAD

**Issue by FarmerMark** [naikus/svg-gauge#41]
Hi 

Changing the value of font-size for .value-text doesn't seem to have any effect on the font size when the label is displayed:

.gauge-container > .gauge > .value-text {
  fill: rgb(47, 227, 255);
  font-family: sans-serif;
  font-weight: bold;
  **font-size: 0.8em;**
}

I've tried using your fiddle demo to and it doesn't have any effect - am I looking at the wrong class?

M.

**Comment by naikus** [comment]
Hi @FarmerMark Thanks for pointing this issue. This popped up because of the recent change to guage's svg structure to support text styling in  Safari. I've fixed the README.md with updated documentation and also fixed the codepen demo.
