### ISSUE TITLE
Use in a vue component?

### ISSUE THREAD

**Issue by martynwheeler** [naikus/svg-gauge#42]
Hi,

Is it possible to use this in a vue component (vue-svg-gauge has some bugs that make it unusable for me)?

Thanks
MArtyn

**Comment by naikus** [comment]
I'm not well versed with Vue but I think it should be possible using the lificycle hooks.
https://vuejs.org/v2/api/#Options-Lifecycle-Hooks

**Comment by martynwheeler** [comment]
@naikus, thanks for your response.  I have managed to use it in a vue component.  One last question, if I may, is it possible to have a gradient fill for the gauge value that is displayed?

**Comment by naikus** [comment]
@martynwheeler It may be possible to do it via style attribute or css class using fill property. But changing it dynamically would be a bit of a task

**Comment by alextbfdigital** [comment]
> @naikus, thanks for your response. I have managed to use it in a vue component. One last question, if I may, is it possible to have a gradient fill for the gauge value that is displayed?

Can you tell me how did you use in vue.js? Can you give me an example?

**Comment by digitalmouse** [comment]
> > @naikus, thanks for your response. I have managed to use it in a vue component. One last question, if I may, is it possible to have a gradient fill for the gauge value that is displayed?
> 
> Can you tell me how did you use in vue.js? Can you give me an example?

Agreed!  Share the love!  :)

**Comment by martynwheeler** [comment]
Hey, sorry but I switched to High charts in my app as it was more flexible. Can't remember what I did now...
