### ISSUE TITLE
Is it possible to display decimals in labels

### ISSUE THREAD

**Issue by gism** [naikus/svg-gauge#44]
Hi, 

This is more a question than an issue.
Is it possible to display decimals in gauge label?

Thanks for the work!

**Comment by naikus** [comment]
@gism 
Yes, use the ```label`` option 
```javascript
    label: function(value) {
      // return Math.round(value) + "/" + this.max;
    },
```
See the demo on codepen https://codepen.io/naikus/pen/BzkoLL
