### ISSUE TITLE
Error: <path> attribute d: Expected number, "…0 A 40 40 0 1 1 NaN NaN".

### ISSUE THREAD

**Issue by codespikex** [naikus/svg-gauge#46]
Facing this error on instantiating svg-gauge.
"Error: <path> attribute d: Expected number, "…0 A 40 40 0 1 1 NaN NaN". "
this setAttribute call is causing the error
 https://github.com/naikus/svg-gauge/blob/ab68cda8413d9ab716d70fde552b04ea96ce6ee0/src/gauge.js#L279

**Comment by naikus** [comment]
@codespikex What browser & version are you facing this issue? Can you create a fiddle?

**Comment by codespikex** [comment]
@naikus sorry wasn't able to reproduce the error on codepen or jsfiddle.
I'm developing an extension and the error is persistent.
You can check the error in the console log of the extension popup

### STEPS TO REPRODUCE USING EXTENSION
1. install the extension 
2. open the popup
3. navigate to the database tab
4. check the console log

[dist-dev.zip](https://github.com/naikus/svg-gauge/files/5663928/dist-dev.zip)

you can also check the gauge component for the extension
https://github.com/codespikex/vu-quiz-assistant/blob/main/src/js/extension/components/quiz/scoreGauge.vue

**Comment by naikus** [comment]
Hi @codespikex 
I saw the code and the problem seems to be this line 
https://github.com/codespikex/vu-quiz-assistant/blob/6734f0e660181ac68eba195549ef7e1b9f413817/src/js/extension/components/quiz/scoreGauge.vue#L40

It should be
```javascript
gauge =  /* new */ Gauge({...props})
```

Can you try it out?

**Comment by codespikex** [comment]
@naikus 
changed
https://github.com/codespikex/vu-quiz-assistant/blob/6734f0e660181ac68eba195549ef7e1b9f413817/src/js/extension/components/quiz/scoreGauge.vue#L40
to
https://github.com/codespikex/vu-quiz-assistant/blob/main/src/js/extension/components/quiz/scoreGauge.vue#L40

but the error is still there

**Comment by naikus** [comment]
@codespikex Thanks for reporting this! The gauge options must contain an initial value via the ```value``` option. You can set it to whatever initial value you like. 
Meanwhile I'll fix it the take a default value. 
Thanks again

P.S. Btw the extension's UI is quite cool!

**Comment by codespikex** [comment]
Thanks for pointing that out.
I was so obvious when i was trying to reproduce it.
