### ISSUE TITLE
Dynamic setMaxValue

### ISSUE THREAD

**Issue by PaoloVIP** [naikus/svg-gauge#51]
Can be setMaxValue dynamic like setValueAnimated or setValue ?

**Comment by luasenvy** [comment]
![image](https://user-images.githubusercontent.com/24634713/118436676-2ef97600-b71c-11eb-967f-2007a3bfb21d.png)

Gauge instance has `setMaxValue` ;)

**Comment by naikus** [comment]
Hi @PaoloVIP 
You can set the max value dynamically and two things will happen:
1. The guage's current dial will be adjusted accordingly (the colored bar)
2. It will not be animated and will update in a single frame

Hence it'd be a good idea to show the current and max value both as part of the label using the ```label``` function


```javascript
var max = getMaxFromSomewhere();
var gauge7 = Gauge(
  document.getElementById("gauge7"), {
    max: max,
    dialStartAngle: -90,
    dialEndAngle: -90.001,
    value: 100,
    showValue: true,
    label: function(value) {
      return `${Math.round(value * 100) / 100} / ${max}`;
    }
  }
);
```
