### ISSUE TITLE
function getGauge(myHtmlElement) like.

### ISSUE THREAD

**Issue by Guillaume-Cecchini** [naikus/svg-gauge#62]
Hello,

Is there a way to do something like this : 
     myGauge = getGauge(document.getElementById("gauge0")).
or myGauge = getGauge(myHtmlElement).

Thank you,

Guillaume.

**Comment by naikus** [comment]
Yes,
You can always name the function as ```getGauge```
```javascript
// Require JS
var getGauge = require("svg-gauge");

// Standalone
var getGauge = window.Gauge;

// Create a new Gauge
var cpuGauge = getGauge(document.getElementById("cpuSpeed"), {
    max: 100,
    value: 50
});
```
