### ISSUE TITLE
Changing the direction of animation

### ISSUE THREAD

**Issue by KPChow** [naikus/svg-gauge#67]
Hiya!

Just wanted to ask if there is, or will be, an option to change the direction of the gauge animating from anti-clockwise to clockwise.

Thanks.

**Comment by KPChow** [comment]
Never mind, I figured it out. 😂

**Comment by naikus** [comment]
How did you do it? Did you invert the colors for dial background and foreground?

**Comment by KPChow** [comment]
@naikus simply not give your gauge a value, just set the min and max.

**Example:**

Gauge(
    gauges[i], {
        min: 0,
        max: 100,
        dialStartAngle: 270,
        dialEndAngle: 269,
        showValue: false
    }
).setValueAnimated(value, 1);

**Comment by naikus** [comment]
Cool!
